#
# EcoWeapons
# by Auxilor
#

discover-recipes: true # If all recipes should be automatically discovered.

cooldown:
  in-actionbar: true
  sound:
    enabled: true
    sound: "BLOCK_NOTE_BLOCK_PLING"
    pitch: 0.5